language: generic
sudo: false
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck
matrix:
  include:
  - name: "health check"
    env: CONFIG=.luacheckrc
  allow_failures:
  - name: "beauty check"
    env: CONFIG=.luacheck_tidy
script: 
- echo $CONFIG .
- $HOME/.luarocks/bin/luacheck -config $CONFIG -files .
notifications:
  email:
    on_failure: change